---  
- name: Install Apache HTTP server  
  hosts: myhosts
  remote_user: aakash  
  become: yes  # This allows you to run the installation with sudo  
  tasks:  
    - name: Ensure httpd is installed  
      apt:   
        name: apache2  
        state: latest  

    - name: Start httpd service  
      service:  
        name: apache2  
        state: started  
        enabled: yes  

